import type { FinanceState } from "@/lib/domain/types";

const updatedAt = "2026-08-02T05:20:00.000Z";

export const demoSeed: FinanceState = {
  fictional: true,
  categories: [
    {
      id: "salary",
      name: "Salary",
      kind: "income",
      colour: "#25745a",
      icon: "wallet",
      includeInReports: true,
    },
    {
      id: "sports-work",
      name: "Sports work",
      kind: "income",
      colour: "#3d8f75",
      icon: "activity",
      includeInReports: true,
    },
    {
      id: "interest",
      name: "Interest",
      kind: "income",
      colour: "#55a98f",
      icon: "trending-up",
      includeInReports: true,
    },
    {
      id: "groceries",
      name: "Groceries",
      kind: "essential",
      colour: "#d68b3c",
      icon: "shopping-basket",
      includeInReports: true,
    },
    {
      id: "housing",
      name: "Housing",
      kind: "essential",
      colour: "#c46b4f",
      icon: "house",
      includeInReports: true,
    },
    {
      id: "transport",
      name: "Transport",
      kind: "essential",
      colour: "#8a7355",
      icon: "car",
      includeInReports: true,
    },
    {
      id: "healthcare",
      name: "Healthcare",
      kind: "essential",
      colour: "#6f84a3",
      icon: "heart-pulse",
      includeInReports: true,
    },
    {
      id: "phone",
      name: "Phone",
      kind: "essential",
      colour: "#61758f",
      icon: "smartphone",
      includeInReports: true,
    },
    {
      id: "dining",
      name: "Dining out",
      kind: "discretionary",
      colour: "#b46c84",
      icon: "utensils",
      includeInReports: true,
    },
    {
      id: "coffee",
      name: "Coffee",
      kind: "discretionary",
      colour: "#9a6b54",
      icon: "coffee",
      includeInReports: true,
    },
    {
      id: "subscriptions",
      name: "Subscriptions",
      kind: "discretionary",
      colour: "#7d6aa6",
      icon: "repeat",
      includeInReports: true,
    },
    {
      id: "travel",
      name: "Travel",
      kind: "discretionary",
      colour: "#4c8c9e",
      icon: "plane",
      includeInReports: true,
    },
    {
      id: "misc",
      name: "Miscellaneous",
      kind: "discretionary",
      colour: "#7a7f86",
      icon: "circle",
      includeInReports: true,
    },
    {
      id: "transfer",
      name: "Internal transfer",
      kind: "transfer",
      colour: "#718096",
      icon: "arrow-left-right",
      includeInReports: false,
    },
    {
      id: "investments",
      name: "Investments",
      kind: "wealth",
      colour: "#335f8a",
      icon: "chart-line",
      includeInReports: true,
    },
    {
      id: "emergency",
      name: "Emergency savings",
      kind: "wealth",
      colour: "#2c7a6b",
      icon: "shield",
      includeInReports: true,
    },
    {
      id: "debt",
      name: "Additional debt repayment",
      kind: "wealth",
      colour: "#8a5a5a",
      icon: "landmark",
      includeInReports: true,
    },
  ],
  accounts: [
    {
      id: "everyday",
      name: "Everyday account",
      institution: "Demo Mutual",
      type: "everyday",
      maskedNumber: "•••• 1842",
      balanceCents: 342860,
      availableBalanceCents: 342860,
      currency: "AUD",
      connected: true,
      includeInNetWorth: true,
      includeInCashFlow: true,
      hidden: false,
      archived: false,
      lastSyncedAt: updatedAt,
    },
    {
      id: "savings",
      name: "Future fund",
      institution: "Demo Mutual",
      type: "savings",
      maskedNumber: "•••• 7710",
      balanceCents: 1275000,
      availableBalanceCents: 1275000,
      currency: "AUD",
      connected: true,
      includeInNetWorth: true,
      includeInCashFlow: true,
      hidden: false,
      archived: false,
      lastSyncedAt: updatedAt,
    },
    {
      id: "credit",
      name: "Rewards card",
      institution: "Example Bank",
      type: "credit_card",
      maskedNumber: "•••• 4406",
      balanceCents: -86430,
      availableBalanceCents: 413570,
      currency: "AUD",
      connected: true,
      includeInNetWorth: true,
      includeInCashFlow: true,
      hidden: false,
      archived: false,
      lastSyncedAt: updatedAt,
    },
  ],
  transactions: [
    {
      id: "tx-salary",
      accountId: "everyday",
      providerId: "demo-001",
      originalDescription: "ACME HEALTH PAYROLL",
      merchant: "Acme Health",
      amountCents: 324000,
      currency: "AUD",
      transactionDate: "2026-07-30",
      postingDate: "2026-07-30",
      categoryId: "salary",
      notes: "",
      tags: ["physiotherapy"],
      status: "posted",
      source: "demo-bank",
      recurring: true,
      transfer: false,
      reimbursement: false,
      refund: false,
      excludedFromReports: false,
      excludedFromCashFlow: false,
      needsReview: false,
      manuallyCategorised: false,
      splits: [],
      updatedAt,
    },
    {
      id: "tx-sports",
      accountId: "everyday",
      providerId: "demo-002",
      originalDescription: "HARBOUR SPORTS CLUB",
      merchant: "Harbour Sports Club",
      amountCents: 46500,
      currency: "AUD",
      transactionDate: "2026-07-27",
      postingDate: "2026-07-28",
      categoryId: "sports-work",
      notes: "Weekend coverage",
      tags: ["irregular-income"],
      status: "posted",
      source: "demo-bank",
      recurring: false,
      transfer: false,
      reimbursement: false,
      refund: false,
      excludedFromReports: false,
      excludedFromCashFlow: false,
      needsReview: false,
      manuallyCategorised: false,
      splits: [],
      updatedAt,
    },
    {
      id: "tx-rent",
      accountId: "everyday",
      providerId: "demo-003",
      originalDescription: "RENT TRANSFER",
      merchant: "Property rent",
      amountCents: -112000,
      currency: "AUD",
      transactionDate: "2026-07-29",
      postingDate: "2026-07-29",
      categoryId: "housing",
      notes: "",
      tags: [],
      status: "posted",
      source: "demo-bank",
      recurring: true,
      transfer: false,
      reimbursement: false,
      refund: false,
      excludedFromReports: false,
      excludedFromCashFlow: false,
      needsReview: false,
      manuallyCategorised: false,
      splits: [],
      updatedAt,
    },
    {
      id: "tx-groceries-1",
      accountId: "credit",
      providerId: "demo-004",
      originalDescription: "WOOLWORTHS 1163",
      merchant: "Woolworths",
      amountCents: -12645,
      currency: "AUD",
      transactionDate: "2026-07-28",
      postingDate: "2026-07-29",
      categoryId: "groceries",
      notes: "",
      tags: [],
      status: "posted",
      source: "demo-bank",
      recurring: false,
      transfer: false,
      reimbursement: false,
      refund: false,
      excludedFromReports: false,
      excludedFromCashFlow: false,
      needsReview: false,
      manuallyCategorised: false,
      ruleId: "rule-woolworths",
      splits: [],
      updatedAt,
    },
    {
      id: "tx-groceries-2",
      accountId: "credit",
      providerId: "demo-005",
      originalDescription: "COLES 0741",
      merchant: "Coles",
      amountCents: -8420,
      currency: "AUD",
      transactionDate: "2026-07-23",
      postingDate: "2026-07-24",
      categoryId: "groceries",
      notes: "",
      tags: [],
      status: "posted",
      source: "demo-bank",
      recurring: false,
      transfer: false,
      reimbursement: false,
      refund: false,
      excludedFromReports: false,
      excludedFromCashFlow: false,
      needsReview: false,
      manuallyCategorised: false,
      splits: [],
      updatedAt,
    },
    {
      id: "tx-dining",
      accountId: "credit",
      providerId: "demo-006",
      originalDescription: "THE GROUNDS CAFE",
      merchant: "The Grounds",
      amountCents: -5890,
      currency: "AUD",
      transactionDate: "2026-07-26",
      postingDate: "2026-07-27",
      categoryId: "dining",
      notes: "Dinner with friends",
      tags: ["social"],
      status: "posted",
      source: "demo-bank",
      recurring: false,
      transfer: false,
      reimbursement: false,
      refund: false,
      excludedFromReports: false,
      excludedFromCashFlow: false,
      needsReview: false,
      manuallyCategorised: true,
      splits: [],
      updatedAt,
    },
    {
      id: "tx-coffee",
      accountId: "credit",
      providerId: "demo-007",
      originalDescription: "NORTHSIDE COFFEE",
      merchant: "Northside Coffee",
      amountCents: -620,
      currency: "AUD",
      transactionDate: "2026-07-31",
      postingDate: "2026-08-01",
      categoryId: "coffee",
      notes: "",
      tags: [],
      status: "posted",
      source: "demo-bank",
      recurring: false,
      transfer: false,
      reimbursement: false,
      refund: false,
      excludedFromReports: false,
      excludedFromCashFlow: false,
      needsReview: false,
      manuallyCategorised: false,
      splits: [],
      updatedAt,
    },
    {
      id: "tx-transport",
      accountId: "everyday",
      providerId: "demo-008",
      originalDescription: "TRANSPORT NSW",
      merchant: "Transport NSW",
      amountCents: -4800,
      currency: "AUD",
      transactionDate: "2026-07-25",
      postingDate: "2026-07-25",
      categoryId: "transport",
      notes: "",
      tags: [],
      status: "posted",
      source: "demo-bank",
      recurring: false,
      transfer: false,
      reimbursement: false,
      refund: false,
      excludedFromReports: false,
      excludedFromCashFlow: false,
      needsReview: false,
      manuallyCategorised: false,
      splits: [],
      updatedAt,
    },
    {
      id: "tx-stream",
      accountId: "credit",
      providerId: "demo-009",
      originalDescription: "STREAMBOX AU",
      merchant: "StreamBox",
      amountCents: -1899,
      currency: "AUD",
      transactionDate: "2026-07-21",
      postingDate: "2026-07-22",
      categoryId: "subscriptions",
      notes: "",
      tags: [],
      status: "posted",
      source: "demo-bank",
      recurring: true,
      transfer: false,
      reimbursement: false,
      refund: false,
      excludedFromReports: false,
      excludedFromCashFlow: false,
      needsReview: false,
      manuallyCategorised: false,
      splits: [],
      updatedAt,
    },
    {
      id: "tx-mobile",
      accountId: "credit",
      providerId: "demo-010",
      originalDescription: "MOBILE CO",
      merchant: "Mobile Co",
      amountCents: -4500,
      currency: "AUD",
      transactionDate: "2026-07-18",
      postingDate: "2026-07-19",
      categoryId: "phone",
      notes: "",
      tags: [],
      status: "posted",
      source: "demo-bank",
      recurring: true,
      transfer: false,
      reimbursement: false,
      refund: false,
      excludedFromReports: false,
      excludedFromCashFlow: false,
      needsReview: false,
      manuallyCategorised: false,
      splits: [],
      updatedAt,
    },
    {
      id: "tx-transfer-out",
      accountId: "everyday",
      providerId: "demo-011",
      originalDescription: "TRANSFER TO FUTURE FUND",
      merchant: "Future fund",
      amountCents: -75000,
      currency: "AUD",
      transactionDate: "2026-07-30",
      postingDate: "2026-07-30",
      categoryId: "emergency",
      notes: "Monthly savings",
      tags: [],
      status: "posted",
      source: "demo-bank",
      recurring: true,
      transfer: true,
      reimbursement: false,
      refund: false,
      excludedFromReports: false,
      excludedFromCashFlow: true,
      needsReview: false,
      manuallyCategorised: false,
      linkedTransferId: "tx-transfer-in",
      splits: [],
      updatedAt,
    },
    {
      id: "tx-transfer-in",
      accountId: "savings",
      providerId: "demo-012",
      originalDescription: "TRANSFER FROM EVERYDAY",
      merchant: "Everyday account",
      amountCents: 75000,
      currency: "AUD",
      transactionDate: "2026-07-30",
      postingDate: "2026-07-30",
      categoryId: "transfer",
      notes: "",
      tags: [],
      status: "posted",
      source: "demo-bank",
      recurring: true,
      transfer: true,
      reimbursement: false,
      refund: false,
      excludedFromReports: false,
      excludedFromCashFlow: true,
      needsReview: false,
      manuallyCategorised: false,
      linkedTransferId: "tx-transfer-out",
      splits: [],
      updatedAt,
    },
    {
      id: "tx-card-payment-out",
      accountId: "everyday",
      providerId: "demo-013",
      originalDescription: "CREDIT CARD PAYMENT",
      merchant: "Rewards card",
      amountCents: -92000,
      currency: "AUD",
      transactionDate: "2026-07-20",
      postingDate: "2026-07-20",
      categoryId: "transfer",
      notes: "",
      tags: [],
      status: "posted",
      source: "demo-bank",
      recurring: true,
      transfer: true,
      reimbursement: false,
      refund: false,
      excludedFromReports: false,
      excludedFromCashFlow: true,
      needsReview: false,
      manuallyCategorised: false,
      linkedTransferId: "tx-card-payment-in",
      splits: [],
      updatedAt,
    },
    {
      id: "tx-card-payment-in",
      accountId: "credit",
      providerId: "demo-014",
      originalDescription: "PAYMENT RECEIVED",
      merchant: "Everyday account",
      amountCents: 92000,
      currency: "AUD",
      transactionDate: "2026-07-20",
      postingDate: "2026-07-20",
      categoryId: "transfer",
      notes: "",
      tags: [],
      status: "posted",
      source: "demo-bank",
      recurring: true,
      transfer: true,
      reimbursement: false,
      refund: false,
      excludedFromReports: false,
      excludedFromCashFlow: true,
      needsReview: false,
      manuallyCategorised: false,
      linkedTransferId: "tx-card-payment-out",
      splits: [],
      updatedAt,
    },
    {
      id: "tx-review",
      accountId: "credit",
      providerId: "demo-015",
      originalDescription: "SQ *MKT 00429",
      merchant: "Unknown merchant",
      amountCents: -7350,
      currency: "AUD",
      transactionDate: "2026-07-31",
      postingDate: "2026-08-01",
      categoryId: "misc",
      notes: "",
      tags: [],
      status: "posted",
      source: "demo-bank",
      recurring: false,
      transfer: false,
      reimbursement: false,
      refund: false,
      excludedFromReports: false,
      excludedFromCashFlow: false,
      needsReview: true,
      manuallyCategorised: false,
      splits: [],
      updatedAt,
    },
  ],
  rules: [
    {
      id: "rule-woolworths",
      name: "Woolworths groceries",
      field: "description",
      operator: "contains",
      value: "WOOLWORTHS",
      categoryId: "groceries",
      priority: 10,
      enabled: true,
    },
    {
      id: "rule-transport",
      name: "Public transport",
      field: "merchant",
      operator: "contains",
      value: "Transport",
      categoryId: "transport",
      priority: 20,
      enabled: true,
    },
  ],
  goals: [
    {
      id: "goal-emergency",
      name: "Emergency fund",
      description: "A calm buffer for unexpected expenses.",
      targetCents: 1500000,
      currentCents: 975000,
      targetDate: "2027-02-28",
      priority: "high",
      linkedAccountId: "savings",
      allocatedCents: 975000,
      contributionFrequency: "monthly",
      plannedContributionCents: 75000,
      notes: "Aim for around four months of essentials.",
      status: "active",
      createdAt: "2025-09-01",
    },
    {
      id: "goal-travel",
      name: "Japan trip",
      description: "Flights, accommodation and spending buffer.",
      targetCents: 650000,
      currentCents: 300000,
      targetDate: "2027-06-01",
      priority: "medium",
      linkedAccountId: "savings",
      allocatedCents: 300000,
      contributionFrequency: "fortnightly",
      plannedContributionCents: 20000,
      notes: "",
      status: "active",
      createdAt: "2026-01-12",
    },
  ],
  holdings: [
    {
      id: "holding-ioo",
      name: "iShares Global 100 ETF",
      ticker: "IOO",
      exchange: "ASX",
      assetClass: "International shares",
      units: 42.5,
      averagePriceCents: 10840,
      currentPriceCents: 12160,
      platform: "Demo Brokerage",
      currency: "AUD",
      notes: "Fictional holding",
      lastPriceUpdate: "2026-08-01",
      archived: false,
    },
    {
      id: "holding-ivv",
      name: "iShares S&P 500 ETF",
      ticker: "IVV",
      exchange: "ASX",
      assetClass: "International shares",
      units: 18,
      averagePriceCents: 5300,
      currentPriceCents: 5980,
      platform: "Demo Brokerage",
      currency: "AUD",
      notes: "Fictional holding",
      lastPriceUpdate: "2026-08-01",
      archived: false,
    },
  ],
  liabilities: [
    {
      id: "hecs",
      name: "HECS–HELP",
      type: "hecs_help",
      balanceCents: 2865000,
      includeInNetWorth: true,
      notes: "Manual fictional balance; update from official statement.",
      updatedAt: "2026-06-01",
    },
  ],
  assets: [
    {
      id: "super",
      name: "Example Super",
      type: "superannuation",
      valueCents: 2940000,
      includeInNetWorth: true,
      liquid: false,
      notes: "Manual fictional balance",
      updatedAt: "2026-07-31",
    },
  ],
  plans: [
    {
      month: "2026-08",
      overallTargetCents: 220000,
      intendedSavingsRate: 0.3,
      intendedSavingsCents: 110000,
      intendedInvestmentCents: 40000,
      categories: [
        { categoryId: "housing", targetCents: 112000, rollover: false },
        { categoryId: "groceries", targetCents: 42000, rollover: false },
        { categoryId: "transport", targetCents: 18000, rollover: false },
        { categoryId: "dining", targetCents: 24000, rollover: false },
        { categoryId: "subscriptions", targetCents: 12000, rollover: false },
      ],
    },
  ],
  recurring: [
    {
      id: "rec-rent",
      merchant: "Property rent",
      expectedCents: 112000,
      minCents: 112000,
      maxCents: 112000,
      frequency: "monthly",
      nextExpectedDate: "2026-08-29",
      categoryId: "housing",
      accountId: "everyday",
      active: true,
      confidence: 0.99,
      lastObservedDate: "2026-07-29",
    },
    {
      id: "rec-mobile",
      merchant: "Mobile Co",
      expectedCents: 4500,
      minCents: 4500,
      maxCents: 4500,
      frequency: "monthly",
      nextExpectedDate: "2026-08-18",
      categoryId: "phone",
      accountId: "credit",
      active: true,
      confidence: 0.96,
      lastObservedDate: "2026-07-18",
    },
  ],
  subscriptions: [
    {
      id: "sub-stream",
      merchant: "StreamBox",
      amountCents: 1899,
      frequency: "monthly",
      nextChargeDate: "2026-08-21",
      accountId: "credit",
      categoryId: "subscriptions",
      previousAmountCents: 1699,
      lastObservedDate: "2026-07-21",
      cancelled: false,
      notes: "Price increased by $2 last month.",
    },
    {
      id: "sub-cloud",
      merchant: "Cloud Notes",
      amountCents: 9999,
      frequency: "annual",
      nextChargeDate: "2026-09-14",
      accountId: "credit",
      categoryId: "subscriptions",
      lastObservedDate: "2025-09-14",
      cancelled: false,
      notes: "Annual renewal approaching.",
    },
  ],
  netWorthSnapshots: [
    { date: "2026-02-28", assetsCents: 6370000, liabilitiesCents: 3080000, netWorthCents: 3290000 },
    { date: "2026-03-31", assetsCents: 6530000, liabilitiesCents: 3040000, netWorthCents: 3490000 },
    { date: "2026-04-30", assetsCents: 6680000, liabilitiesCents: 3010000, netWorthCents: 3670000 },
    { date: "2026-05-31", assetsCents: 6910000, liabilitiesCents: 2980000, netWorthCents: 3930000 },
    { date: "2026-06-30", assetsCents: 7170000, liabilitiesCents: 2940000, netWorthCents: 4230000 },
    { date: "2026-07-31", assetsCents: 8200000, liabilitiesCents: 2951430, netWorthCents: 5248570 },
  ],
  reviews: [],
  notifications: [
    {
      id: "notice-review",
      title: "One transaction needs review",
      message: "Check the unknown merchant from 31 July.",
      level: "review",
      createdAt: updatedAt,
      dismissed: false,
      href: "/transactions",
    },
    {
      id: "notice-sub",
      title: "Subscription price changed",
      message: "StreamBox increased by $2.00 this month.",
      level: "info",
      createdAt: "2026-07-22T04:00:00.000Z",
      dismissed: false,
      href: "/reports",
    },
  ],
  preferences: {
    currency: "AUD",
    dateFormat: "DD/MM/YYYY",
    financialYearStartsInJuly: true,
    theme: "system",
    notifications: { sync: true, review: true, forecast: true, goals: true, subscriptions: true },
  },
  bankConnection: {
    id: "demo-connection",
    institution: "Demo Mutual + Example Bank",
    status: "connected",
    lastSyncedAt: updatedAt,
    environment: "synthetic-demo",
  },
};
